// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-L6zRfHerniXRDKTh37vfb4smDxmthUo',
    appId: '1:623609718768:web:d5440dad35816c15e81f35',
    messagingSenderId: '623609718768',
    projectId: 'sistema-financeiro-3d9ee',
    authDomain: 'sistema-financeiro-3d9ee.firebaseapp.com',
    storageBucket: 'sistema-financeiro-3d9ee.firebasestorage.app',
    measurementId: 'G-9HSYY10BED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQ4AKwaKAQ-rdrQjYZtuMlTQAnmUltSU',
    appId: '1:623609718768:android:e90a952439a6a38ee81f35',
    messagingSenderId: '623609718768',
    projectId: 'sistema-financeiro-3d9ee',
    storageBucket: 'sistema-financeiro-3d9ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsveypjcIxjrCgitDV88Pv1ZGm9NM_nTk',
    appId: '1:623609718768:ios:b5967d2ad3232e81e81f35',
    messagingSenderId: '623609718768',
    projectId: 'sistema-financeiro-3d9ee',
    storageBucket: 'sistema-financeiro-3d9ee.firebasestorage.app',
    iosBundleId: 'com.example.sistemaFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsveypjcIxjrCgitDV88Pv1ZGm9NM_nTk',
    appId: '1:623609718768:ios:b5967d2ad3232e81e81f35',
    messagingSenderId: '623609718768',
    projectId: 'sistema-financeiro-3d9ee',
    storageBucket: 'sistema-financeiro-3d9ee.firebasestorage.app',
    iosBundleId: 'com.example.sistemaFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-L6zRfHerniXRDKTh37vfb4smDxmthUo',
    appId: '1:623609718768:web:253904dfe4f145aae81f35',
    messagingSenderId: '623609718768',
    projectId: 'sistema-financeiro-3d9ee',
    authDomain: 'sistema-financeiro-3d9ee.firebaseapp.com',
    storageBucket: 'sistema-financeiro-3d9ee.firebasestorage.app',
    measurementId: 'G-9SLSBCBYV7',
  );
}
